config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 devise_for :users
  root to: 'homes#top'
  get "home/about"=>"homes#about"

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end



  # ネストさせる
  resources :users, only: [:index,:show,:edit,:update] do
  #フォローする、外す(いいね関係と同じでresourceに注意)
    resource :relationships, only: [:create, :destroy]
  #フォローした人一覧
    get 'followings' => 'relationships#followings', as: 'followings'
  #フォローされた人一覧
    get 'followers' => 'relationships#followers', as: 'followers'
 end

 get '/search' => 'searches#search'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.comments.new(comment_params)
    @comment.book_id = @book.id
    unless @comment.save
      render 'error'  #comments/error.js.erbを参照する 
    end
      #redirect_to request.referer
      #comments/create.js.erbを参照する
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    comment = @book.comments.find(params[:id])
    comment.destroy
    #redirect_to request.referer
    #comments/destroy.js.erbを参照する
  end


  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_index.html.erb
<% book.comments.each do |comment| %>
  <% comment_user = comment.user %>
  <tr>
  	<td>
  		<%= link_to user_path(comment_user), class: "user_#{comment_user.id}" do %>
    		<%= image_tag comment.user.get_profile_image %><br>
    		<%= comment_user.name %>
  		<% end %>
  	</td>
  	<td><%= comment.comment %></td>
  	<% if current_user == comment_user %>
    	<td><%= link_to 'Destroy', book_comment_path(comment.book_id, comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
  	<% end %>
  </tr>
<% end %>

app/views/comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.comments.count %>");
$(".book_comments").html("<%= j(render 'comments/index', book: @book) %>");
$("#comment_comment").val("");

app/views/comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.comments.count %>");
$(".book_comments").html("<%= j(render 'comments/index', book: @book) %>");
$("#comment_comment").val("");

app/views/comments/error.js.erb
<!--prependはhtmlと違い、子要素の最初に差し込む。-->
$(".body > .container").prepend("<%= j(render 'layouts/errors', obj: @comment) %>");