config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 devise_for :users
  root to: 'homes#top'
  get "home/about"=>"homes#about"

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end



  # ネストさせる
  resources :users, only: [:index,:show,:edit,:update] do
  #フォローする、外す(いいね関係と同じでresourceに注意)
    resource :relationships, only: [:create, :destroy]
  #フォローした人一覧
    get 'followings' => 'relationships#followings', as: 'followings'
  #フォローされた人一覧
    get 'followers' => 'relationships#followers', as: 'followers'
 end

 get '/search' => 'searches#search'

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books ,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  #フォローの関係(２行目は一覧画面で使う)自分がフォローする
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following

  #フォロワーの関係(２行目は一覧画面で使う)自分がフォローされる
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms　

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end


  def follow!(user)
    following_relationships.create!(following_id: user.id)
  end

  def unfollow!(user)
    relation = following_relationships.find_by!(following_id: user.id)
    relation.destroy!
  end

  def following?(user)
    followings.include?(user)
    #following_relationships.exists?(following_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    elsif method == "partial"
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit,:update]


  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

    #特定の日に保存された投稿数
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    #今週、前週
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_create_book.html.erb
<div class="mt-5">
  <h2>投稿数の前日比、前週比</h2>
  <div class="table">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </tr>
      </thead>
      
      <tbody>
        <tr>
          <td><%= @today_book.count %></td>
          <td><%= @yesterday_book.count %></td>
          <td>
            <% if @yesterday_book.count == 0 %>
              前日の投稿はありません
            <% else %>
            <!--to_fメソッドはオブジェクトの少数点までの数値も表示-->
            <!--前日比　=　昨日の投稿数÷前日の投稿数-->
              <% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
            <!--roundメソッドで四捨五入-->
         　    <%= (@the_day_before * 100).round %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>今週の投稿数</th>
          <th>前週の投稿数</th>
          <th>前週比</th>
        </tr>
      </thead>
      
      <tbody>
        <tr>
          <td><%= @this_week_book.count %></td>
          <td><%= @last_week_book .count %></td>
          <td>
            <% if @last_week_book.count == 0 %>
              前週の投稿はありません
            <% else %>
            <!--to_fメソッドはオブジェクトの少数点までの数値も表示-->
            <!--前週比　=　今週の投稿数÷先週の投稿数-->
              <% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
            <!--roundメソッドで四捨五入-->
         　    <%= (@the_week_before * 100).round %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>Followers</th>
    <th>
      <%= link_to user_followers_path(user.id) do%>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>

  <tr>
    <th> Followings</th>
  　<th>
      <%= link_to user_followings_path(user.id) do%>
       <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
<% if user == current_user %>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
<%else %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete ,class: "btn btn-info"%>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post,class: "btn btn-info" %>
  <% end %>
  <% if current_user.following?(user) && user.following?(current_user) %>
  <%= link_to 'chatを始める', chat_path(user.id), class: "ml-2" %>
  <% end %>
<% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <%= render 'users/create_book'%>
    </div>
  </div>
</div>